In [11]:
import numpy as np
np.random.seed(42)
n_players = 1000
X = np.random.rand(n_players,3)
X[:,0] *= 5000
X[:, 1] *= 100
X[:,2] *= 150

true_w = np.array([0.5, 20, 10])
intersept = 500

y = (X@true_w + intersept)+np.random.normal(0, 50, size=n_players)

print(f"X shape: {X.shape}\ny shape: {y.shape}\nX: {X[:5]}\n\n\ny: {y[:5]}")

X shape: (1000, 3)
y shape: (1000,)
X: [[1.87270059e+03 9.50714306e+01 1.09799091e+02]
 [2.99329242e+03 1.56018640e+01 2.33991781e+01]
 [2.90418061e+02 8.66176146e+01 9.01672518e+01]
 [3.54036289e+03 2.05844943e+00 1.45486478e+02]
 [4.16221320e+03 2.12339111e+01 2.72737451e+01]]


y: [4488.76664186 2573.52556936 3313.41230575 3697.91742576 3339.11947344]
